import { useMemo, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, Clock3, Edit3, GraduationCap, Megaphone, Plus, Sparkles, Trash2, Users, X } from "lucide-react";
import { addOpportunity, deleteOpportunity, getMyData, getOpportunities, updateOpportunity, getState, getIndustryOpportunityParticipants, updateOpportunityRegistration } from "../services/store";

type Mode = "Internship" | "Workshop" | "Training";
const meta:Record<Mode,{icon:any;action:string;description:string}>={
 Internship:{icon:GraduationCap,action:"Apply",description:"A real internship application and review workflow."},
 Workshop:{icon:CalendarDays,action:"Register",description:"An event or learning experience with attendee registration."},
 Training:{icon:BookOpen,action:"Register",description:"A structured program with completion tracking and certification eligibility."}
};
const blank={title:"",company:"",description:"",skills:"",eligibility:"",duration:"",startDate:"",endDate:"",location:"",workMode:"Remote",stipend:"",openings:"",deadline:"",audience:"Both",department:"",trainer:"",speaker:"",startTime:"",endTime:"",capacity:"",registrationDeadline:"",objectives:"",completionCriteria:""};

function Field({label,value,onChange,type="text",placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <div><label className="label">{label}</label><input className="input" type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></div>}

export function IndustryOpportunityStudio(){
 const me:any=getMyData(); const [mode,setMode]=useState<Mode>("Internship"); const [form,setForm]=useState<any>({...blank,company:me?.profile?.companyName||"NovaTech Labs"}); const [editing,setEditing]=useState<string|null>(null); const [managing,setManaging]=useState<any>(null); const [tick,setTick]=useState(0); const [viewing,setViewing]=useState<any>(null); const [notice,setNotice]=useState("");
 const own=useMemo(()=>getOpportunities().filter((o:any)=>o.company===me?.profile?.companyName),[me?.profile?.companyName,notice,tick]);
 const set=(k:string,v:string)=>setForm((x:any)=>({...x,[k]:v}));
 const save=(publish=true)=>{
   if(!form.title.trim()||!form.description.trim()||!form.skills.trim()){setNotice("Title, description and at least one required skill are mandatory.");return;}
   if(mode==="Internship" && (!form.startDate||!form.endDate||!form.openings)){setNotice("Internships require start date, end date and number of openings.");return;}
   if(mode==="Workshop" && (!form.startDate||!form.startTime||!form.endTime||!form.capacity)){setNotice("Workshops require date, start/end time and maximum participants.");return;}
   if(mode==="Training" && (!form.startDate||!form.endDate||!form.trainer||!form.completionCriteria)){setNotice("Trainings require dates, trainer and completion criteria.");return;}
   const common:any={title:form.title.trim(),company:form.company||me?.profile?.companyName||me?.name||"Industry Partner",description:form.description.trim(),skills:form.skills.split(",").map((x:string)=>x.trim()).filter(Boolean),eligibility:form.eligibility||"Eligible learners",duration:form.duration,location:form.location||"Online",workMode:form.workMode,deadline:form.deadline||form.registrationDeadline||"",registrationDeadline:form.registrationDeadline||form.deadline||"",audience:form.audience,preferredDepartment:form.department||undefined,status:publish?"Published":"Draft",postedAt:new Date().toISOString(),capacity:Number(form.capacity||form.openings)||undefined,engagement:mode==="Internship"?"Application":"Registration",match:0};
   if(mode==="Internship") Object.assign(common,{type:"Internship",compensation:form.stipend||"To be discussed",startDate:form.startDate,endDate:form.endDate,openings:Number(form.openings)||0});
   if(mode==="Workshop") Object.assign(common,{type:"Workshop",compensation:"Free / Industry event",startDate:form.startDate,startTime:form.startTime,endTime:form.endTime,speaker:form.speaker,trainer:form.trainer});
   if(mode==="Training") Object.assign(common,{type:"Training",compensation:"Industry training",startDate:form.startDate,endDate:form.endDate,trainer:form.trainer,learningObjectives:form.objectives.split("\n").map((x:string)=>x.trim()).filter(Boolean),completionCriteria:form.completionCriteria});
   if(editing){updateOpportunity(editing,common);setNotice(`${mode} updated.`);setTick(x=>x+1)}else{addOpportunity(common);setNotice(`${mode} published successfully.`);setTick(x=>x+1)}
   setEditing(null);setForm({...blank,company:me?.profile?.companyName||"NovaTech Labs"});
 };
 const startEdit=(o:any)=>{setMode(o.type as Mode);setEditing(o.id);setForm({...blank,...o,skills:(o.skills||[]).join(", "),stipend:o.compensation||"",openings:String(o.openings||o.capacity||""),capacity:String(o.capacity||""),department:o.preferredDepartment||"",objectives:(o.learningObjectives||[]).join("\n"),completionCriteria:o.completionCriteria||""})};
 const remove=(id:string)=>{deleteOpportunity(id);setNotice("Opportunity deleted.");setTick(x=>x+1)};
 return <div className="space-y-6">
  <div className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-900 p-6 text-white shadow-xl lg:p-8"><div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-cyan-200"><Sparkles size={13}/> Industry publishing center</span><h1 className="mt-4 text-3xl font-black">Post Opportunities</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">One unified space for internships, workshops and trainings. Each opportunity keeps its correct Apply or Register lifecycle.</p></div></div>
  <div className="grid gap-3 md:grid-cols-3">{(Object.keys(meta) as Mode[]).map(k=>{const M=meta[k];const I=M.icon;return <button key={k} onClick={()=>{setMode(k);setEditing(null)}} className={`rounded-2xl border p-5 text-left ${mode===k?"border-violet-400 bg-violet-50":"border-slate-200 bg-white"}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-cyan-300"><I size={18}/></span><h2 className="mt-4 font-black">{k}s</h2><p className="mt-1 text-xs text-slate-500">{M.description}</p><span className="mt-3 inline-flex rounded-full bg-cyan-50 px-2.5 py-1 text-[10px] font-black text-cyan-700">{M.action}</span></button>})}</div>
  <div className="card p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black">{editing?"Edit":"Post"} {mode}</h2><p className="text-sm text-slate-500">Target audience controls who can see and participate.</p></div>{editing&&<button className="btn-secondary" onClick={()=>{setEditing(null);setForm({...blank,company:me?.profile?.companyName||"NovaTech Labs"})}}>Cancel edit</button>}</div>
   <div className="mt-5 grid gap-4 sm:grid-cols-2">
    <Field label={`${mode} title`} value={form.title} onChange={v=>set("title",v)} placeholder={mode==="Internship"?"Frontend Engineering Internship":mode==="Workshop"?"AI Product Building Workshop":"Cloud Fundamentals Training"}/>
    <Field label="Company" value={form.company} onChange={v=>set("company",v)}/>
    <Field label="Location" value={form.location} onChange={v=>set("location",v)} placeholder="Hyderabad / Online"/>
    <div><label className="label">Work mode</label><select className="input" value={form.workMode} onChange={e=>set("workMode",e.target.value)}><option>On-site</option><option>Hybrid</option><option>Remote</option></select></div>
    <div><label className="label">Target audience</label><select className="input" value={form.audience} onChange={e=>set("audience",e.target.value)}><option>Students</option><option>Faculty / Academicians</option><option>Both</option></select></div>
    <Field label="Preferred academic department (optional)" value={form.department} onChange={v=>set("department",v)} placeholder="Computer Science"/>
    <Field label="Eligibility" value={form.eligibility} onChange={v=>set("eligibility",v)} placeholder="Year, branch, experience, prerequisite"/>
    <Field label="Required skills" value={form.skills} onChange={v=>set("skills",v)} placeholder="React, JavaScript, Git"/>
    {mode==="Internship"&&<><Field label="Duration" value={form.duration} onChange={v=>set("duration",v)} placeholder="3 months"/><Field label="Stipend" value={form.stipend} onChange={v=>set("stipend",v)} placeholder="₹20,000/month"/><Field label="Start date" value={form.startDate} onChange={v=>set("startDate",v)} type="date"/><Field label="End date" value={form.endDate} onChange={v=>set("endDate",v)} type="date"/><Field label="Number of openings" value={form.openings} onChange={v=>set("openings",v)} type="number"/><Field label="Application deadline" value={form.deadline} onChange={v=>set("deadline",v)} type="date"/></>}
    {mode==="Workshop"&&<><Field label="Trainer / speaker" value={form.speaker} onChange={v=>set("speaker",v)} placeholder="Speaker name"/><Field label="Date" value={form.startDate} onChange={v=>set("startDate",v)} type="date"/><Field label="Start time" value={form.startTime} onChange={v=>set("startTime",v)} type="time"/><Field label="End time" value={form.endTime} onChange={v=>set("endTime",v)} type="time"/><Field label="Duration" value={form.duration} onChange={v=>set("duration",v)} placeholder="2 hours"/><Field label="Maximum participants" value={form.capacity} onChange={v=>set("capacity",v)} type="number"/><Field label="Registration deadline" value={form.registrationDeadline} onChange={v=>set("registrationDeadline",v)} type="date"/><Field label="Meeting link / venue" value={form.location} onChange={v=>set("location",v)}/></>}
    {mode==="Training"&&<><Field label="Duration" value={form.duration} onChange={v=>set("duration",v)} placeholder="4 weeks"/><Field label="Trainer" value={form.trainer} onChange={v=>set("trainer",v)}/><Field label="Start date" value={form.startDate} onChange={v=>set("startDate",v)} type="date"/><Field label="End date" value={form.endDate} onChange={v=>set("endDate",v)} type="date"/><Field label="Number of seats" value={form.capacity} onChange={v=>set("capacity",v)} type="number"/><Field label="Registration deadline" value={form.registrationDeadline} onChange={v=>set("registrationDeadline",v)} type="date"/><div><label className="label">Learning objectives</label><textarea className="input min-h-24" value={form.objectives} onChange={e=>set("objectives",e.target.value)} placeholder="One objective per line"/></div><div><label className="label">Completion criteria</label><textarea className="input min-h-24" value={form.completionCriteria} onChange={e=>set("completionCriteria",e.target.value)} placeholder="Complete all modules and pass the final assessment"/></div></>}
    <div className="sm:col-span-2"><label className="label">Description</label><textarea className="input min-h-32" value={form.description} onChange={e=>set("description",e.target.value)} placeholder="What will participants do, learn or build?"/></div>
    <div className="sm:col-span-2 flex flex-wrap gap-2"><button className="btn-primary flex-1" onClick={()=>save(true)}><Plus size={16}/>{editing?"Save changes":`Publish ${mode}`}</button>{!editing&&<button className="btn-secondary flex-1" onClick={()=>save(false)}>Save as Draft</button>}</div>
   </div>
   {notice&&<div className="mt-4 flex gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={18}/><span>{notice}</span><button className="ml-auto" onClick={()=>setNotice("")}><X size={15}/></button></div>}
  </div>
  <div><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-black">My Opportunities</h2><p className="text-sm text-slate-500">Draft, Published, Closed and Expired opportunities with live participation counts.</p></div><span className="badge bg-violet-50 text-violet-700">{own.length} total</span></div>
   <div className="grid gap-4 lg:grid-cols-2">{own.map((o:any)=>{const status=o.status||"Published";const liveStatus=status==="Published"&&o.deadline&&o.deadline<new Date().toISOString().slice(0,10)?"Expired":status;const registrations=getState().opportunityRegistrations.filter((r:any)=>r.opportunityId===o.id).length;return <div className="card p-5" key={o.id}><div className="flex items-start justify-between gap-3"><div><span className="badge bg-cyan-50 text-cyan-700">{o.type}</span><h3 className="mt-2 font-black">{o.title}</h3><p className="mt-1 text-sm text-slate-500">{o.description}</p></div><span className="badge bg-emerald-50 text-emerald-700">{liveStatus}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-slate-50 p-3"><Clock3 size={14}/><p className="mt-1 text-slate-400">Deadline</p><b>{o.deadline||o.registrationDeadline||"Open"}</b></div><div className="rounded-xl bg-slate-50 p-3"><Users size={14}/><p className="mt-1 text-slate-400">{o.type==="Internship"?"Openings":"Seats"}</p><b>{o.openings||o.capacity||"Open"}</b></div></div><div className="mt-3 flex flex-wrap gap-1.5">{(o.skills||[]).map((s:string)=><span className="badge bg-slate-100 text-slate-600" key={s}>{s}</span>)}</div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setManaging(o)}>Manage</button><button className="btn-secondary" onClick={()=>setViewing(o)}>View</button><button className="btn-secondary" onClick={()=>startEdit(o)}><Edit3 size={14}/> Edit</button><button className="btn-secondary" onClick={()=>{updateOpportunity(o.id,{status:liveStatus==="Published"?"Closed":"Published"});setNotice(liveStatus==="Published"?"Opportunity closed.":"Opportunity published.");setTick(x=>x+1)}}><Megaphone size={14}/>{status==="Published"?"Close":"Publish"}</button><button className="btn-secondary" onClick={()=>remove(o.id)}><Trash2 size={14}/> Delete</button><span className="badge bg-slate-100 text-slate-600">{o.type==="Internship"?"Applications":"Registrations"}: {registrations}</span><span className="ml-auto badge bg-violet-50 text-violet-700">Action: {o.engagement}</span></div></div>})}</div>
   {!own.length&&<div className="card p-8 text-center text-sm text-slate-500">No opportunities yet.</div>}
  </div>
  {managing&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><span className="badge bg-cyan-50 text-cyan-700">{managing.type}</span><h2 className="mt-2 text-xl font-black">Manage {managing.type==="Internship"?"applications":"registrations"}</h2><p className="text-sm text-slate-500">{managing.title}</p></div><button onClick={()=>setManaging(null)}><X/></button></div><div className="mt-5 space-y-3">{getIndustryOpportunityParticipants(managing.id).map((r:any)=><div className="rounded-xl border p-4" key={r.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{r.learner?.name||"Learner"}</b><p className="text-xs text-slate-500">{r.learner?.role==="faculty"?"Faculty / Academician":"Student"} · {r.learner?.email}</p></div><select className="input w-auto" value={r.status} onChange={e=>{updateOpportunityRegistration(r.id,e.target.value as any);setTick(x=>x+1)}}><option>Registered</option><option>In Progress</option><option>Completed</option><option>Rejected</option></select></div></div>)}{!getIndustryOpportunityParticipants(managing.id).length&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No workshop/training registrations yet. Internship applications are managed in Recruitment Pipeline.</p>}</div></div></div>}
  {viewing&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><span className="badge bg-cyan-50 text-cyan-700">{viewing.type}</span><h2 className="mt-2 text-2xl font-black">{viewing.title}</h2><p className="text-sm text-slate-500">{viewing.company}</p></div><button onClick={()=>setViewing(null)}><X/></button></div><p className="mt-5 text-sm leading-6 text-slate-600">{viewing.description}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 text-sm">{[["Eligibility",viewing.eligibility],["Audience",viewing.audience],["Location",viewing.location],["Deadline",viewing.deadline||viewing.registrationDeadline||"Open"],["Skills",(viewing.skills||[]).join(", ")],["Status",viewing.status||"Published"]].map(([a,b])=><div className="rounded-xl bg-slate-50 p-3" key={String(a)}><p className="text-xs text-slate-400">{a}</p><b>{b||"—"}</b></div>)}</div></div></div>}
 </div>
}
